spring:
  application:
    name: SpringLAgenda
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringLAgenda?useSSL=false&serverTimezone=true&serverTimezone=UTC
    username: root
    password: Luis1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false